### ISSUE TITLE
Shadowmap on ios

### ISSUE THREAD

**Issue by oosmoxiecode** [expo/expo-three#38] opened 2018-04-11 09:38 UTC
Hi, I am having an issue getting shadows to work on my ios device(iphone se, ios 11.3). Made a simple scene to illustrate the problem, the topleft image on the screenshots below is the output of the shadowcamera.

When running examples from threejs.org in the browser the shadows works as expected.
Anyone else had problems like that?
Any ideas what could be causing it?

Thanks!

Ios:
![shadowmap_ios](https://user-images.githubusercontent.com/513079/38608346-61dc4db8-3d7b-11e8-929e-1ee829609642.png)

Works on android:
![shadowmap_android](https://user-images.githubusercontent.com/513079/38608376-72c3fb62-3d7b-11e8-8d55-9e972eb434cd.png)

**Comment by EvanBacon** [comment] 2018-04-13 20:44
This problem came in SDK 25 when we shifted to using the native iOS framebuffer. I haven't tested to see if this was fixed in 26 - where we added support for OpenGL-ES 3 / WebGL 2.0.

**Comment by SvenJonsson** [comment] 2018-04-14 05:33
I have the same problem at SDK 26, tried downgrading to expo SDK 24 and then SDK 23 but the issue remained to me. Can you confirm? @EvanBacon 

![ios shadowmap](https://user-images.githubusercontent.com/8920853/38764812-d175710a-3ff0-11e8-8e1b-7de78d107c4f.PNG)

**Comment by EvanBacon** [comment] 2018-05-09 02:03
@SvenJonsson unfortunately EXGL versions work a little differently than the rest of Expo. EXGL is C++ that is used across both android and iOS, then bridged through the respective platforms, so downgrading doesn't work the same. 
I'll take another stab at this tonight.

**Comment by EvanBacon** [comment] 2018-05-09 02:51
lol figured it out... just add this line before building the renderer, works on both platforms:
```js
gl.createRenderbuffer = (() => ({}));
```
https://snack.expo.io/@bacon/three-shadows
![img_0096](https://user-images.githubusercontent.com/9664363/39793177-2a33fddc-52f9-11e8-80b0-9f5aa1b807b5.PNG)

**Closed by EvanBacon** 2018-05-09 02:51 UTC

**Comment by bberak** [comment] 2018-12-25 07:04
Hi @EvanBacon  and @oosmoxiecode,

Did you find anything fishing going on with the z-depth/buffer after applying this fix?

Specifically, I'm finding the z-order gets messed up when using this fix and the EffectComposer with at least one shader pass.

Here is what my app looks like without any shader passes being applied. Notice the orange box gets rendered **behind** the blue platform when it falls.

![correct-z-depth](https://user-images.githubusercontent.com/1929971/50415277-41826480-086e-11e9-903e-56d89cba4dda.gif)

Here is the same code with an additional sepia shader pass added to the effect composer. Notice that the box gets rendered incorrectly **in front** of the platform when it falls.

![incorrect-z-depth](https://user-images.githubusercontent.com/1929971/50415282-4b0bcc80-086e-11e9-9d65-27d20954e5fa.gif)

Removing the ```gl.createRenderbuffer = (() => ({}));``` line fixes the z-depth issue, but it causes other problems with shadows and some other shaders down the line.

I've tried this on both Expo SDK 27 and Expo SDK 31 - I get the same results.

Thanks in advance for any ideas/clues - and many thanks for all your work.

**Comment by tsapeta** [comment] 2020-03-31 08:08
Hey guys, sorry for late reaction, but this issue comes like a boomerang so I investigated it more now 😄 
My guess is that it's a duplicate of https://github.com/expo/expo/issues/7502, so please see my comment there: https://github.com/expo/expo/issues/7502#issuecomment-606250452

If anyone is still working on it and can let me know whether the workaround works I'd be very grateful 🙏
